#include<stdio.h>
int main(){
    int a[2][2],b[2][2],c[2][2],i,j,k;
    printf("enter 1st matrix:\n");
    for(i=0;i<2;i++){
        for(j=0;j<2;j++){
        scanf("%d",&a[i][j]);
        }
    }
    printf("enter 2nd matrix:\n");
    for(i=0;i<2;i++){
        for(j=0;j<2;j++){
        scanf("%d",&b[i][j]);
        }
    }
    for(i=0;i<2;i++){
        for(j=0;j<2;j++){
            c[i][j]=a[i][j]+b[i][j];
        }
        printf("\n");
    }
    printf("add\n");
    for(i=0;i<2;i++){
        for(j=0;j<2;j++){
            printf("%d\t",c[i][j]);
        }
    }
    printf("\n");
    for(i=0;i<2;i++){
        for(j=0;j<2;j++){
            c[i][j]=a[i][j]-b[i][j];
        }
    }
    printf("substraction\n");
    for(i=0;i<2;i++){
        for(j=0;j<2;j++){
            printf("%d\t",c[i][j]);
        }
        printf("\n");
    }
        for(i=0;i<2;i++){
        for(j=0;j<2;j++){
            c[i][j]=0;
        }
    }
    for(i=0;i<2;i++){
        for(j=0;j<2;j++){
            for(int k=0;k<2;k++){
            c[i][j]+=a[i][k]*b[k][j];
        }
    }
}
  printf("multilply\n");
  for(i=0;i<2;i++){
        for(j=0;j<2;j++){
            printf("%d\t",c[i][j]);
        }
    printf("\n");
    }
}